resources:

- name: repo
  type: git
  source:
    uri: https://github.com/fusion-com-au/concourse-rancher-compose-resource
    branch: master

- name: image
  type: docker-image
  source:
    email: {{dockerhub_email}}
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}
    repository: fusioncomau/concourse-rancher-compose-resource

jobs:

- name: test
  public: true
  plan:

  - get: repo
    trigger: true

  - task: run tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: mhart/alpine-node, tag: "6"}
      inputs:
        - name: repo
      run:
        path: sh
        args:
          - -exc
          - |
            cd repo
            npm install
            npm test

- name: build
  public: true
  plan:

  - get: repo
    trigger: true
    passed: [test]

  - put: image
    params:
      build: repo
